require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/barmen", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Barman. As you add validations to Barman, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    Hash[name: "John", salary: 1000, age: 25]
  }

  let(:invalid_attributes) {
    {name: '', age: 2, salary: -2}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Barman.create! valid_attributes
      get barmen_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      barman = Barman.create! valid_attributes
      get barman_url(barman)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_barman_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      barman = Barman.create! valid_attributes
      get edit_barman_url(barman)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Barman" do
        expect {
          post barmen_url, params: { barman: valid_attributes }
        }.to change(Barman, :count).by(1)
      end

      it "redirects to the created barman" do
        post barmen_url, params: { barman: valid_attributes }
        expect(response).to redirect_to(barman_url(Barman.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Barman" do
        expect {
          post barmen_url, params: { barman: invalid_attributes }
        }.to change(Barman, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post barmen_url, params: { barman: invalid_attributes }
        expect(response).to have_http_status(422)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested barman" do
        barman = Barman.create! valid_attributes
        patch barman_url(barman), params: { barman: new_attributes }
        barman.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the barman" do
        barman = Barman.create! valid_attributes
        patch barman_url(barman), params: { barman: new_attributes }
        barman.reload
        expect(response).to redirect_to(barman_url(barman))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        barman = Barman.create! valid_attributes
        patch barman_url(barman), params: { barman: invalid_attributes }
        expect(response).to have_http_status(422)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested barman" do
      barman = Barman.create! valid_attributes
      expect {
        delete barman_url(barman)
      }.to change(Barman, :count).by(-1)
    end

    it "redirects to the barmen list" do
      barman = Barman.create! valid_attributes
      delete barman_url(barman)
      expect(response).to redirect_to(barmen_url)
    end
  end
end
