require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cashboxes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Cashbox. As you add validations to Cashbox, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {money: 15}
  }

  let(:invalid_attributes) {
    {money: nil}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cashbox.create! valid_attributes
      get cashboxes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cashbox = Cashbox.create! valid_attributes
      get cashbox_url(cashbox)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cashbox_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cashbox = Cashbox.create! valid_attributes
      get edit_cashbox_url(cashbox)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cashbox" do
        expect {
          post cashboxes_url, params: { cashbox: valid_attributes }
        }.to change(Cashbox, :count).by(1)
      end

      it "redirects to the created cashbox" do
        post cashboxes_url, params: { cashbox: valid_attributes }
        expect(response).to redirect_to(cashbox_url(Cashbox.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cashbox" do
        expect {
          post cashboxes_url, params: { cashbox: invalid_attributes }
        }.to change(Cashbox, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cashboxes_url, params: { cashbox: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cashbox" do
        cashbox = Cashbox.create! valid_attributes
        patch cashbox_url(cashbox), params: { cashbox: new_attributes }
        cashbox.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cashbox" do
        cashbox = Cashbox.create! valid_attributes
        patch cashbox_url(cashbox), params: { cashbox: new_attributes }
        cashbox.reload
        expect(response).to redirect_to(cashbox_url(cashbox))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cashbox = Cashbox.create! valid_attributes
        patch cashbox_url(cashbox), params: { cashbox: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cashbox" do
      cashbox = Cashbox.create! valid_attributes
      expect {
        delete cashbox_url(cashbox)
      }.to change(Cashbox, :count).by(-1)
    end

    it "redirects to the cashboxes list" do
      cashbox = Cashbox.create! valid_attributes
      delete cashbox_url(cashbox)
      expect(response).to redirect_to(cashboxes_url)
    end
  end
end
